title: jcan310
url: 'https://jcan310.github.io/Website/'
author: Anjaecheol
email: jcan321@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

social:
  twitter: jcan310
  facebook: jcan310
  instagram: ironmonst
  github: jcan310
  linkedin: jcan310

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
